name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Read node version from `.nvmrc` file
      - id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvmrc.outputs.node_version }}'
      - run: yarn
      - run: yarn test

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linter:
          - eslint
          - prettier
          - tsc
    steps:
      - uses: actions/checkout@v2
      # Read node version from `.nvmrc` file
      - id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvmrc.outputs.node_version }}'
      - run: yarn
      - run: |
          yarn lint:${{ matrix.linter }}

  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    if: github.ref == 'refs/heads/main'
    needs:
      - test
      - lint
    steps:
      - uses: actions/checkout@v2
      # Read node version from `.nvmrc` file
      - id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvmrc.outputs.node_version }}'
      - name: Install Deps
        run: yarn
      - name: Deploy
        run: yarn deploy
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
